dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel_2.0.0-linux-x86_64.deb
  - sha256sum -c bazel/bazel_2.0.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_2.0.0-linux-x86_64.deb
  - cp .bazelrc_travis .bazelrc

script:
  - bazel test //atc/... -c opt --python_version=py3 --test_output=errors --curses=no
